### ISSUE TITLE
birthDate field no longer in personStatements

### ISSUE THREAD

**Issue by kd-ods** [openownership/register-transformer-dk#14]
Looking at the [fields in personStatements](https://bods-data.openownership.org/source/denmark/#table-person_statement), as of 26th June 2023, no birthDate is there.

This field was in the data previously (since it is integral to one of the queries run for the [DK Dashboard notebook](https://deepnote.com/@open-ownership/Denmark-CVR-dashboard-9c2835e6-cecb-4d70-9e6f-bde86f6dfdd7)).

We need to investigate whether this data is no longer included in the source, or hasn't been mapped for some reason.

**Comment by StephenAbbott** [comment]
@kd-ods Apologies for wasting your time on this. Have realised that we must have copied the birth date query in the Denmark dashboard notebook over from [UK PSC dashboard](https://deepnote.com/@open-ownership/UK-PSC-dashboard-2a4e8e4e-492e-48cb-891c-34b1d852dbfd) and [Slovakia](https://deepnote.com/@open-ownership/Slovakia-RPVS-dashboard-fb4b6afa-2b39-4261-baaf-887071a2d62d) dashboard - and I assumed it worked for DK so reported this as broken earlier.

[This code](https://github.com/openownership/register-transformer-dk/blob/701c7db03446d6cd2fd2bd94ca75ca93a31e6369/lib/register_transformer_dk/bods_mapping/person_statement.rb#L115) in the [register-transformer-dk repo](https://github.com/openownership/register-transformer-dk/) shows DK register doesn't have `birthDate` for BOs which you can also see from person pages on the live Register where Danish BOs have no birth date displaying (see [example](https://register.openownership.org/entities/5b5f62369dfc3fae185f3d09)).
